### ISSUE TITLE
Y-axis counts for small numbers

### ISSUE THREAD

**Issue by mdbarnesUCSD** [AlexandrovLab/SigProfilerPlotting#19]
SigProfilerPlotting: 1.2.2

Issue: Y-axis tick values for small values (ie values <10) showing up as 00k.

Example below:
![SBS_96_plots_test_png](https://user-images.githubusercontent.com/22506723/177374496-897e9f47-77c8-4f22-9148-58ab5bccda28.jpg)

**Comment by rvangara** [comment]
The latest version of SigProfilerPlotting(v1.3) should resolve the issue. Please reopen the ticket if the issue persists. 
![SBS_96_plots_BRCA_example_Page_1](https://user-images.githubusercontent.com/15685272/196754208-8c1fcbec-28ce-4e6d-8f67-5b608aacabf1.png)
