### ISSUE TITLE
Templates cannot be created when SigProfilerPlotting is containerised

### ISSUE THREAD

**Issue by mvforster** [AlexandrovLab/SigProfilerPlotting#38]
Dear Team,

 I have attempted to create a container encompassing as many of the SigProfiler tools as possible for deployment within an Air-Gapped analysis environment.

The container errors out when SigProfilerPlotting needs to produce the templates needed for the plotting to take place.
The stack trace is:
`Traceback (most recent call last):
File "/usr/local/lib/python3.9/dist-packages/sigProfilerPlotting/sigProfilerPlotting.py", line 1027, in plotSBS
fig_orig=make_pickle_file(context='SBS96', return_plot_template=True, volume=volume)
File "/usr/local/lib/python3.9/dist-packages/sigProfilerPlotting/sigProfilerPlotting.py", line 129, in make_pickle_file
os.mkdir(volume)
OSError: [Errno 30] Read-only file system: '/usr/local/lib/python3.9/dist-packages/sigProfilerPlotting/templates/'`

Looking into the code in your project it appear that the following line:
`SPP_TEMPLATES = os.path.join(SPP_PATH, "templates/")`
shows that the templates directory needs to be created in the install location of the package. This is not possible within the read-only filesystem of a container. 

I have attempted to work around the issue by editing this line to be:
`SPP_TEMPLATES = os.path.join(".", "templates/")` and use the current working directory as the template root but I am not sure if there are other functions that need to be changed.

Would it be possible to:
- confirm the number of locations where such write operations are likely to run into errors?
- update the code to allow the templates directory to be configured as a user-defined location?

Many thanks for your assistance,
Best wishes,

Matthieu

**Comment by mdbarnesUCSD** [comment]
Hi @mvforster,

There is a parameter "volume" for plotSBS, plotDBS, or plotID that should resolve this issue. The parameter sets a custom destination for the templates to be saved and loaded from. This parameter is not yet documented and has had minimal testing. Please do reach out if you encounter any issues.

**Comment by mvforster** [comment]
Dear @mdbarnesUCSD,

Thanks for this suggestion. I will check the code and see how this parameter can be passed in within my existing container and will report the results back to you if that will help you with your documentation.

Best wishes,

Matthieu

**Comment by mdbarnesUCSD** [comment]
Please re-open if you encounter any issues.

**Comment by mvforster** [comment]
Dear @mdbarnesUCSD,

Many thanks for your assistance and please accept my apologies for the delay.

The main difficulty that I am coming across is in passing in the template location. For context sigProfilerPlotting is not being called directly but as part of SigProfilerAssingment. I have been trying to track down the interaction between these two packages to see how the SigProfilerAssignment function can take in the parameter needed.

I have been able to overcome the problem that I was facing by editing the sigProfilerPlotter.py script as part of the container build process.

I believe that at this point this is an issue with SigProfilerAssignment not having the ability to take in the templates location as a variable. I think that I will either need to raise an issue with that project or potentially try to fix this and make a pull request.

Given the above, I agree that the issue should remain closed but will be happy to answer any questions that may arise on this matter.

Wishing you success with your ongoing work.

Best wishes,

Matthieu

**Comment by mdbarnesUCSD** [comment]
Great, glad to hear about your interest in this functionality. We are currently in the process of making similar changes to SigProfilerMatrixGenerator. Once those updates are made, we will be updating [SigProfilerAssignment](https://github.com/AlexandrovLab/SigProfilerAssignment/tree/vol_update) and SigProfilerExtractor to incorporate these changes (both tools require plotting and matrix generation).
