### ISSUE TITLE
division by zero

### ISSUE THREAD

**Issue by litd** [AlexandrovLab/SigProfilerPlotting#4]
File "/miniconda3/lib/python3.6/site-packages/sigProfilerPlotting/sample_portrait.py", line 2033, in samplePortrait
    panel7.bar(x, mutations_78[sample][key][seq]/total_count*100,width=0.4,color=colors[i],align='center', zorder=1000)
ZeroDivisionError: float division by zero

have a few divided by zero issues when using percentage=True in plotting.

**Comment by ebergstr** [comment]
Thank you for the feedback. This should be fixed in version 1.0.9

**Comment by litd** [comment]
Thanks! Would you please also fix this issue in
sigPlt.plotID/SBS/DBS
ZeroDivisionError: float division by zero
errpr mesg: There may be an issue with the formatting of you matrix file.
