### ISSUE TITLE
error in pip install

### ISSUE THREAD

**Issue by gsteinhardt** [AlexandrovLab/SigProfilerPlotting#5]
I was able to install the following using pip within my conda env:

SigProfilerMatrixGenerator
sigproextractor
sigproSS

but somehow pip didn't work for plotting:

_pip install SigProfilePlotting
Collecting SigProfilePlotting
  ERROR: Could not find a version that satisfies the requirement SigProfilePlotting (from versions: none)
ERROR: No matching distribution found for SigProfilePlotting_

It could be my a version type problem but if the rest of them worked, not sure what I am missing for this plotting module. there was an issue with my matrix generator install (issue submitted on that github page), not sure if my workaround is causing this problem.
thanks

**Comment by ebergstr** [comment]
It appears you spelled the package name wrong. It should be changed from pip install SigProfilePlotting to pip install SigProfilerPlotting

**Comment by t-silvers** [comment]
this typo is still in the README 🍻
